on:
  pull_request:
    branches:
      - master

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Master
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_SECRET }}
          server-dir: public/
